version: '2'
services:
    mysql:
        build: ./src/main/docker/mysql
        container_name: "mysql-sprzecior"
#        volumes:
#            - ./ci/.data/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - nginx-proxy
    app:
        build: .
        container_name: sprzecior_app
        command: bash -c "./start.sh && mvn spring-boot:run -DskipTests=true"
        links:
            - mysql
        networks:
            - nginx-proxy
        environment:
            - VIRTUAL_HOST=$CI_PROJECT_NAMESPACE.$CI_PROJECT_NAME.b2.etd24.pl
            - VIRTUAL_PORT=8080

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
